### ISSUE TITLE
Enabling the authentication on firebase console

### ISSUE THREAD

**Issue by alialsaeedi19** [BME-MIT-IET/eng1-iet-2018#4]
For using the authentication service of firebase you have first to enable it from the console.
Also enable the anonymous for entering the app as guest.
<img width="1285" alt="screen shot 2018-04-26 at 11 37 40 pm" src="https://user-images.githubusercontent.com/21360696/39333393-fdf0d724-49aa-11e8-82b4-7103501493f8.png">

**Comment by wschenbuer** [comment]
thanks!

**Comment by BoqianHan** [comment]
Its help me,thanks
