### ISSUE TITLE
Performing manual code review on the application

### ISSUE THREAD

**Issue by alialsaeedi19** [BME-MIT-IET/eng1-iet-2018#6]
Perform some code review and try to fix some parts.

**Comment by maamjadi** [comment]
@alialsaeedi19 yes sure I will check the analysis now and add the issues as soon as tmrw

**Comment by maamjadi** [comment]
@alialsaeedi19 I have pushed the code for sonar to the new branch and everything is set and ready.
also I am gonna create another issue to say how you can run and test it on yours
